name: Build
description: "Build Purescript App"
inputs:
  node-version:
    description: "NodeJS version https://github.com/marketplace/actions/setup-node-js-environment#supported-version-syntax"
    required: true
    default: "latest"
  build-dir:
    description: "Target directory for build. Default `dist`."
    required: false
    default: "dist"
  entry-html:
    description: "Entry HTML file. Default `public/index.html`"
    required: false
    default: "public/index.html"
runs:
  using: composite
  steps:
    - name: Set up Node toolchain
      uses: actions/setup-node@v1
      with:
        node-version: ${{ inputs.node-version }}

    - name: Cache PureScript dependencies
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-spago-${{ hashFiles('**/*.dhall') }}
        path: |
          .spago
          output

    - name: Cache NPM dependencies
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Install NPM dependencies
      shell: bash
      run: |
        npm install -g purescript spago esbuild parcel
        npm install

    - name: Build the project
      shell: bash
      run: |
        rm -rf ${{ inputs.build-dir }}
        mkdir -p ${{ inputs.build-dir }} 
        cp ${{ inputs.entry-html }} ${{ inputs.build-dir }}/ 
        spago bundle-app --to ${{ inputs.build-dir }}/index.js 
        parcel build ${{ inputs.build-dir }}/index.html
