name: Build
description: "Build Purescript App"
inputs:
  node-version:
    description: "NodeJS version https://github.com/marketplace/actions/setup-node-js-environment#supported-version-syntax"
    required: true
    default: "latest"
  build-dir:
    description: "Target directory for build. Default `dist`."
    required: false
    default: "dist"
  public-dir:
    description: "Public directory. Action will copy all folders/files in this directory to build-dir. Default `public`"
    required: false
    default: "public"
runs:
  using: composite
  steps:
    - name: Set up Node toolchain
      uses: actions/setup-node@v1
      with:
        node-version: ${{ inputs.node-version }}

    - name: Cache PureScript dependencies
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-spago-${{ hashFiles('**/*.dhall') }}
        path: |
          .spago
          output

    - name: Cache NPM dependencies
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Install NPM dependencies
      shell: bash
      run: |
        npm install -g purescript spago esbuild parcel
        npm install

    - name: Build the project
      shell: bash
      run: |
        rm -rf ${{ inputs.build-dir }}
        cp -r ${{ inputs.public-dir }} ${{ inputs.build-dir }}
        spago bundle-app --to ${{ inputs.build-dir }}/index.js 
        parcel build ${{ inputs.build-dir }}/index.html
