name: Build
description: "Build Purescript App"
runs:
  using: composite
  steps:
    - name: Set up Node toolchain
      uses: actions/setup-node@v1
      with:
        node-version: "16.x"

    - name: Cache PureScript dependencies
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-spago-${{ hashFiles('**/*.dhall') }}
        path: |
          .spago
          output

    - name: Cache NPM dependencies
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Install NPM dependencies
      shell: bash
      run: |
        npm install -g purescript spago esbuild parcel
        npm install

    - name: Build the project
      shell: bash
      run: |
        rm -rf dist
        mkdir -p dist 
        cp public/index.html dist/ 
        spago bundle-app --to dist/index.js 
        parcel build dist/index.html
